#' Simulated two-period panel for LeeDiD examples
#'
#' A small simulated panel matching the data shape `leedid()` expects: a
#' balanced two-period panel with a time-invariant group assignment, an
#' outcome that is missing whenever either of two selection sources
#' indicates non-selection, and a heterogeneous treatment effect among the
#' treated group in the post-treatment period. Generated by
#' `data-raw/simulate_data.R`; **not** derived from any real dataset.
#'
#' @format A data frame with 1600 rows (800 units x 2 periods) and 6 columns:
#' \describe{
#'   \item{id}{Unit identifier.}
#'   \item{time}{Period: `1` (pre-treatment) or `2` (post-treatment).}
#'   \item{group}{Time-invariant treatment assignment: `0` (control) or
#'     `1` (treated).}
#'   \item{y}{Outcome, `NA` whenever `employed == 0` or `responded == 0`.}
#'   \item{employed}{First selection source (0/1).}
#'   \item{responded}{Second selection source (0/1).}
#' }
#' @examples
#' data(leedid_sim)
#' head(leedid_sim)
"leedid_sim"
